/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.domain.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroCarActivity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4134227177976625611L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroCarActivity\",\"namespace\":\"com.example.domain.tracker\",\"fields\":[{\"name\":\"carID\",\"type\":\"string\"},{\"name\":\"time\",\"type\":\"string\"},{\"name\":\"trace\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroTracePoint\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"time\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence carID;
  @Deprecated public java.lang.CharSequence time;
  @Deprecated public java.util.List<AvroTracePoint> trace;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroCarActivity() {}

  /**
   * All-args constructor.
   * @param carID The new value for carID
   * @param time The new value for time
   * @param trace The new value for trace
   */
  public AvroCarActivity(java.lang.CharSequence carID, java.lang.CharSequence time, java.util.List<AvroTracePoint> trace) {
    this.carID = carID;
    this.time = time;
    this.trace = trace;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return carID;
    case 1: return time;
    case 2: return trace;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: carID = (java.lang.CharSequence)value$; break;
    case 1: time = (java.lang.CharSequence)value$; break;
    case 2: trace = (java.util.List<AvroTracePoint>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'carID' field.
   * @return The value of the 'carID' field.
   */
  public java.lang.CharSequence getCarID() {
    return carID;
  }

  /**
   * Sets the value of the 'carID' field.
   * @param value the value to set.
   */
  public void setCarID(java.lang.CharSequence value) {
    this.carID = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.CharSequence getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.CharSequence value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'trace' field.
   * @return The value of the 'trace' field.
   */
  public java.util.List<AvroTracePoint> getTrace() {
    return trace;
  }

  /**
   * Sets the value of the 'trace' field.
   * @param value the value to set.
   */
  public void setTrace(java.util.List<AvroTracePoint> value) {
    this.trace = value;
  }

  /**
   * Creates a new AvroCarActivity RecordBuilder.
   * @return A new AvroCarActivity RecordBuilder
   */
  public static AvroCarActivity.Builder newBuilder() {
    return new AvroCarActivity.Builder();
  }

  /**
   * Creates a new AvroCarActivity RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroCarActivity RecordBuilder
   */
  public static AvroCarActivity.Builder newBuilder(AvroCarActivity.Builder other) {
    return new AvroCarActivity.Builder(other);
  }

  /**
   * Creates a new AvroCarActivity RecordBuilder by copying an existing AvroCarActivity instance.
   * @param other The existing instance to copy.
   * @return A new AvroCarActivity RecordBuilder
   */
  public static AvroCarActivity.Builder newBuilder(AvroCarActivity other) {
    return new AvroCarActivity.Builder(other);
  }

  /**
   * RecordBuilder for AvroCarActivity instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroCarActivity>
    implements org.apache.avro.data.RecordBuilder<AvroCarActivity> {

    private java.lang.CharSequence carID;
    private java.lang.CharSequence time;
    private java.util.List<AvroTracePoint> trace;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroCarActivity.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.carID)) {
        this.carID = data().deepCopy(fields()[0].schema(), other.carID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.time)) {
        this.time = data().deepCopy(fields()[1].schema(), other.time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.trace)) {
        this.trace = data().deepCopy(fields()[2].schema(), other.trace);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroCarActivity instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroCarActivity other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.carID)) {
        this.carID = data().deepCopy(fields()[0].schema(), other.carID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.time)) {
        this.time = data().deepCopy(fields()[1].schema(), other.time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.trace)) {
        this.trace = data().deepCopy(fields()[2].schema(), other.trace);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'carID' field.
      * @return The value.
      */
    public java.lang.CharSequence getCarID() {
      return carID;
    }

    /**
      * Sets the value of the 'carID' field.
      * @param value The value of 'carID'.
      * @return This builder.
      */
    public AvroCarActivity.Builder setCarID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.carID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'carID' field has been set.
      * @return True if the 'carID' field has been set, false otherwise.
      */
    public boolean hasCarID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'carID' field.
      * @return This builder.
      */
    public AvroCarActivity.Builder clearCarID() {
      carID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.CharSequence getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public AvroCarActivity.Builder setTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.time = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public AvroCarActivity.Builder clearTime() {
      time = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'trace' field.
      * @return The value.
      */
    public java.util.List<AvroTracePoint> getTrace() {
      return trace;
    }

    /**
      * Sets the value of the 'trace' field.
      * @param value The value of 'trace'.
      * @return This builder.
      */
    public AvroCarActivity.Builder setTrace(java.util.List<AvroTracePoint> value) {
      validate(fields()[2], value);
      this.trace = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'trace' field has been set.
      * @return True if the 'trace' field has been set, false otherwise.
      */
    public boolean hasTrace() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'trace' field.
      * @return This builder.
      */
    public AvroCarActivity.Builder clearTrace() {
      trace = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public AvroCarActivity build() {
      try {
        AvroCarActivity record = new AvroCarActivity();
        record.carID = fieldSetFlags()[0] ? this.carID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.time = fieldSetFlags()[1] ? this.time : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.trace = fieldSetFlags()[2] ? this.trace : (java.util.List<AvroTracePoint>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
